import type { Metadata } from "next";
import Link from "next/link";
import { and, desc, gt, isNull } from "drizzle-orm";
import { Breadcrumb } from "@/components/Breadcrumb";
import { SectionHeading } from "@/components/SectionHeading";
import { db } from "@/db";
import { products } from "@/db/schema";
import { getPromoBanners } from "@/lib/db-queries/storefront";
import { formatPrice } from "@/lib/utils/format";

export const dynamic="force-dynamic";
export const metadata: Metadata = { title: "Offers & Installment Plans", description: "Current AutoX Parts Store offers and discounted products." };

export default async function OffersPage(){const[banners,sale]=await Promise.all([getPromoBanners(),db.query.products.findMany({where:and(gt(products.discount,0),isNull(products.archivedAt)),orderBy:[desc(products.updatedAt)],limit:24,with:{brand:true,images:{orderBy:(img,{asc})=>[asc(img.sortOrder)],limit:1}}})]);return <><main><div className="mx-auto max-w-[1600px] px-4 lg:px-6"><Breadcrumb items={[{label:"Home",href:"/"},{label:"Offers"}]}/></div><section className="mx-auto max-w-[1600px] px-4 pb-8 lg:px-6"><h1 className="mb-6 text-2xl font-extrabold text-white">Offers</h1>{banners.length>0?<div className="grid gap-4 md:grid-cols-2">{banners.map(b=><article key={b.id} className="relative min-h-48 overflow-hidden rounded-2xl border border-autox-border bg-autox-panel"><img src={b.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-40"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/75 to-transparent"/><div className="relative z-10 max-w-md p-6"><h2 className="text-xl font-extrabold text-white">{b.title}</h2>{b.description&&<p className="mt-2 text-sm text-autox-gray">{b.description}</p>}{b.ctaHref&&<Link href={b.ctaHref} className="mt-4 inline-flex rounded-xl bg-autox-red px-4 py-2.5 text-xs font-bold uppercase text-white">{b.ctaLabel||'View Offer'}</Link>}</div></article>)}</div>:<p className="rounded-2xl border border-autox-border bg-autox-panel p-5 text-sm text-autox-gray">No promotional banners are active right now.</p>}</section><section className="mx-auto max-w-[1600px] px-4 pb-14 lg:px-6"><SectionHeading title="On" accent="Sale"/>{sale.length>0?<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">{sale.map(p=><Link key={p.id} href={`/products/${p.slug}`} className="group overflow-hidden rounded-2xl border border-autox-border bg-autox-panel transition-colors hover:border-autox-red/60"><div className="relative aspect-square bg-autox-panel3">{p.images[0]&&<img src={p.images[0].url} alt={p.images[0].alt} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"/>}<span className="absolute left-2 top-2 rounded-xl bg-autox-red px-2 py-1 text-[10px] font-extrabold text-white">{p.discount}% OFF</span></div><div className="p-3"><p className="text-[10px] uppercase text-autox-gray">{p.brand.name}</p><h3 className="mt-1 line-clamp-2 text-sm font-semibold text-white">{p.name}</h3><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className="font-extrabold text-white">{formatPrice(p.price)}</span>{p.previousPrice&&<span className="text-xs text-autox-gray line-through">{formatPrice(p.previousPrice)}</span>}</div></div></Link>)}</div>:<p className="text-sm text-autox-gray">No discounted products are active right now.</p>}</section></main></>}
