"use client";

import { useState } from "react";
import { useAppUI } from "@/components/ui/AppUIProvider";
import { MapPin, Pencil, Plus, Trash2, X } from "lucide-react";

type A={id?:string;label:string;line1:string;line2:string|null;city:string;district:string;postalCode:string|null;phone:string;isDefault:boolean};
const empty:A={label:'Home',line1:'',line2:'',city:'',district:'',postalCode:'',phone:'',isDefault:false};
const input='w-full rounded-xl border border-autox-border bg-autox-panel3 px-3 py-2.5 text-sm text-white outline-none focus:border-autox-red';

export function AddressManager({initial}:{initial:A[]}){const{confirm,toast}=useAppUI();
  const[rows,setRows]=useState(initial);const[edit,setEdit]=useState<A|null>(null);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
  const reload=async()=>{const r=await fetch('/api/account/addresses',{cache:'no-store'});if(r.ok){const d=await r.json();setRows(d.addresses??[]);}};
  const save=async()=>{if(!edit)return;setBusy(true);const r=await fetch('/api/account/addresses',{method:edit.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMsg(d.error||'Unable to save');return}await reload();setEdit(null);setMsg('Address saved. Your default address will be used automatically at checkout.');};
  const del=async(id?:string)=>{if(!id)return;const ok=await confirm({title:'Delete address?',description:'This saved address will be removed from your address book. Existing orders keep their delivery snapshot.',confirmLabel:'Delete Address',destructive:true});if(!ok)return;setBusy(true);const r=await fetch(`/api/account/addresses?id=${id}`,{method:'DELETE'});setBusy(false);if(!r.ok){setMsg('Unable to delete address.');toast('Unable to delete address.','error');return;}await reload();setMsg('Address deleted.');toast('Address deleted.','success');};
  return <div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setEdit({...empty})} className="flex items-center gap-2 rounded-xl bg-autox-red px-4 py-2.5 text-xs font-bold text-white"><Plus size={15}/> Add Address</button></div>{msg&&<p className="text-xs text-autox-gray">{msg}</p>}<div className="grid gap-4 md:grid-cols-2">{rows.map(a=><div key={a.id} className={`rounded-2xl border bg-autox-panel p-5 ${a.isDefault?'border-autox-red/50':'border-autox-border'}`}><div className="flex justify-between gap-3"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-autox-red/10 text-autox-red"><MapPin size={18}/></span><div><div className="flex flex-wrap gap-2"><h3 className="font-bold text-white">{a.label}</h3>{a.isDefault&&<span className="rounded-xl bg-autox-red/10 px-2 py-1 text-[9px] font-bold uppercase text-autox-red">Default</span>}</div><p className="mt-2 text-xs leading-5 text-autox-gray">{a.line1}{a.line2?`, ${a.line2}`:''}<br/>{a.city}, {a.district}{a.postalCode?` ${a.postalCode}`:''}<br/>{a.phone}</p></div></div><div className="flex gap-1"><button onClick={()=>setEdit({...a})} className="h-8 w-8 rounded-xl border border-autox-border text-autox-gray hover:border-autox-red hover:text-white"><Pencil size={13} className="mx-auto"/></button><button disabled={busy} onClick={()=>del(a.id)} className="h-8 w-8 rounded-xl border border-autox-border text-autox-red disabled:opacity-50"><Trash2 size={13} className="mx-auto"/></button></div></div></div>)}</div>{rows.length===0&&<div className="rounded-2xl border border-dashed border-autox-border bg-autox-panel p-8 text-center text-sm text-autox-gray">No saved addresses yet.</div>}{edit&&<div className="fixed inset-0 z-[100] overflow-y-auto bg-black/75 p-4"><div className="mx-auto mt-12 max-w-2xl rounded-2xl border border-autox-border bg-autox-panel p-5"><div className="mb-4 flex justify-between"><h2 className="font-bold text-white">{edit.id?'Edit':'Add'} Address</h2><button onClick={()=>setEdit(null)}><X className="text-autox-gray"/></button></div><div className="grid gap-3 md:grid-cols-2">{(['label','line1','line2','city','district','postalCode','phone'] as const).map(k=><label key={k} className={k==='line1'?'md:col-span-2':''}><span className="mb-1 block text-[10px] font-bold uppercase text-autox-gray">{k.replace(/([A-Z])/g,' $1')}</span><input className={input} value={(edit[k]??'') as string} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<label className="flex items-center gap-2 text-sm text-white"><input type="checkbox" checked={edit.isDefault} onChange={e=>setEdit({...edit,isDefault:e.target.checked})}/> Set as default delivery address</label></div><div className="mt-5 flex justify-end"><button disabled={busy} onClick={save} className="rounded-xl bg-autox-red px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50">{busy?'Saving...':'Save Address'}</button></div></div></div>}</div>;
}
