"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { Check, Heart, PackagePlus, ShoppingCart, Trash2, X } from "lucide-react";
import { Breadcrumb } from "@/components/Breadcrumb";
import { EmptyState } from "@/components/ui/EmptyState";
import { ButtonLink } from "@/components/ui/Button";
import { PriceDisplay } from "@/components/ui/PriceDisplay";
import { Rating } from "@/components/ui/Rating";
import { LoadingState } from "@/components/ui/LoadingState";
import { useAppUI } from "@/components/ui/AppUIProvider";
import { setSavedMembership } from "@/lib/client/saved-products-cache";

type Item={id:string;product:{id:string;slug:string;name:string;price:number;previousPrice:number|null;rating:number;reviewCount:number;partType:string;stock:number;warranty:string;brand:{name:string};images:{url:string;alt:string}[];specifications:{id:string;label:string;value:string}[]}};

export default function ComparePage(){
  const {data:session,status}=useSession(); const router=useRouter(); const {toast,confirm}=useAppUI();
  const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true); const [busyId,setBusyId]=useState<string|null>(null); const [wishlisted,setWishlisted]=useState<Set<string>>(new Set()); const [cartAdded,setCartAdded]=useState<string|null>(null);
  useEffect(()=>{if(status==="unauthenticated"||(status==="authenticated"&&(!session?.user?.id||session.user.invalidated))){router.push('/login?callbackUrl=/compare');return}if(status!=="authenticated")return;Promise.all([fetch('/api/compare',{cache:'no-store'}),fetch('/api/wishlist',{cache:'no-store'})]).then(async([compareRes,wishRes])=>{const compareData=compareRes.ok?await compareRes.json():{items:[]};const wishData=wishRes.ok?await wishRes.json():{items:[]};setItems(compareData.items||[]);setWishlisted(new Set<string>((wishData.items||[]).map((x:{product:{id:string}})=>x.product.id)));}).finally(()=>setLoading(false));},[status,session?.user?.id,session?.user?.invalidated,router]);
  const specs=useMemo(()=>Array.from(new Set(items.flatMap(i=>i.product.specifications.map(s=>s.label)))),[items]);
  const details: { label: string; render: (product: Item['product']) => React.ReactNode }[] = [
    { label: 'Price', render: (product) => <PriceDisplay price={product.price} previousPrice={product.previousPrice ?? undefined} size="sm" /> },
    { label: 'Rating', render: (product) => <Rating value={product.rating} reviewCount={product.reviewCount} /> },
    { label: 'Part Type', render: (product) => product.partType.replaceAll('_', ' ') },
    { label: 'Availability', render: (product) => product.stock > 0 ? `${product.stock} in stock` : 'Out of stock' },
    { label: 'Warranty', render: (product) => product.warranty },
    ...specs.map((label) => ({ label, render: (product: Item['product']) => product.specifications.find((spec) => spec.label === label)?.value || '—' })),
  ];
  const remove=async(id:string)=>{setBusyId(id);const res=await fetch(`/api/compare/${id}`,{method:'DELETE'}).catch(()=>null);setBusyId(null);if(!res?.ok){toast('Unable to remove this product from comparison.','error');return;}setItems(x=>x.filter(i=>i.product.id!==id));setSavedMembership('compare',id,false);window.dispatchEvent(new Event('autox-compare-updated'));toast('Removed from comparison.','success');};
  const clearAll=async()=>{const ok=await confirm({title:'Clear comparison?',description:'Remove all products from your current comparison.',confirmLabel:'Clear All',destructive:true});if(!ok)return;for(const item of items){await fetch(`/api/compare/${item.product.id}`,{method:'DELETE'});setSavedMembership('compare',item.product.id,false);}setItems([]);window.dispatchEvent(new Event('autox-compare-updated'));toast('Comparison cleared.','success');};
  const addToCart=async(id:string)=>{setBusyId(id);const res=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id,quantity:1})}).catch(()=>null);setBusyId(null);if(!res?.ok){toast('Unable to add this product to your cart.','error');return;}setCartAdded(id);window.dispatchEvent(new Event('autox-cart-updated'));toast('Added to cart.','success');window.setTimeout(()=>setCartAdded(v=>v===id?null:v),1200);};
  const toggleWishlist=async(id:string)=>{const next=!wishlisted.has(id);setBusyId(id);const res=await fetch(next?'/api/wishlist':`/api/wishlist/${id}`,{method:next?'POST':'DELETE',headers:next?{'Content-Type':'application/json'}:undefined,body:next?JSON.stringify({productId:id}):undefined}).catch(()=>null);setBusyId(null);if(!res?.ok){toast('Unable to update your wishlist.','error');return;}setWishlisted(prev=>{const copy=new Set(prev);if(next)copy.add(id);else copy.delete(id);return copy});setSavedMembership('wishlist',id,next);window.dispatchEvent(new Event('autox-wishlist-updated'));toast(next?'Saved to wishlist.':'Removed from wishlist.','success');};
  if(status==="loading"||loading)return <main><LoadingState label="Loading comparison..."/></main>;
  return <main><div className="mx-auto max-w-[1600px] px-4 lg:px-6"><Breadcrumb items={[{label:'Home',href:'/'},{label:'Compare'}]}/></div><section className="mx-auto max-w-[1600px] px-4 pb-14 lg:px-6">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-autox-red">Side-by-side</p><div className="mt-1 flex items-center gap-3"><h1 className="text-2xl font-extrabold text-white">Compare Parts</h1><span className="rounded-full border border-autox-red/25 bg-autox-red/10 px-2.5 py-1 text-[11px] font-black text-autox-red">{items.length} / 4</span></div><p className="mt-1 text-sm text-autox-gray">See the details that matter before you choose.</p></div><div className="flex gap-2">{items.length>1&&<button type="button" onClick={clearAll} className="flex h-10 items-center gap-2 rounded-lg border border-white/10 px-3 text-xs font-bold text-zinc-400 hover:border-autox-red/40 hover:text-white"><Trash2 size={14}/>Clear All</button>}<ButtonLink href="/products" variant="outline" size="sm"><PackagePlus size={14}/>Add Products</ButtonLink></div></div>
    {items.length===0?<div className="rounded-2xl border border-dashed border-white/10 bg-white/[.02] py-4"><EmptyState title="Nothing to compare yet" description="Select up to four products and compare price, fitment, stock and specifications." action={<ButtonLink href="/products">Browse Products</ButtonLink>}/></div>:<>
      <div className="space-y-4 lg:hidden">
        <div className="autox-overlay-scroll flex snap-x gap-3 overflow-x-auto pb-2">{items.map(({product})=><article key={product.id} className="relative w-[72vw] max-w-[290px] shrink-0 snap-start overflow-hidden rounded-2xl border border-white/[.08] bg-[#0b0b0d] p-3"><button disabled={busyId===product.id} onClick={()=>remove(product.id)} aria-label={`Remove ${product.name}`} className="absolute right-2 top-2 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-black/70 text-zinc-400 hover:text-autox-red"><X size={16}/></button><Link href={`/products/${product.slug}`}>{product.images[0]&&<img src={product.images[0].url} alt={product.images[0].alt} className="aspect-square w-full rounded-xl object-cover"/>}<p className="mt-3 line-clamp-2 min-h-10 text-sm font-bold text-white">{product.name}</p><p className="mt-1 text-[11px] text-zinc-500">{product.brand.name}</p></Link><div className="mt-2"><PriceDisplay price={product.price} previousPrice={product.previousPrice??undefined} size="sm"/></div><div className="mt-3 grid grid-cols-[1fr_42px] gap-2"><button disabled={busyId===product.id||product.stock<=0} onClick={()=>addToCart(product.id)} className="flex h-10 items-center justify-center gap-1.5 rounded-lg bg-autox-red text-[10px] font-black uppercase text-white disabled:opacity-40">{cartAdded===product.id?<><Check size={14}/>Added</>:<><ShoppingCart size={14}/>Add to Cart</>}</button><button disabled={busyId===product.id} onClick={()=>toggleWishlist(product.id)} aria-label="Toggle wishlist" className="flex h-10 items-center justify-center rounded-lg border border-white/10 text-zinc-400 hover:text-autox-red"><Heart size={16} className={wishlisted.has(product.id)?'fill-autox-red text-autox-red':''}/></button></div></article>)}</div>
        <div className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#0b0b0d]">{details.map(({label,render})=><div key={label} className="border-b border-white/[.07] p-4 last:border-b-0"><p className="mb-3 text-[10px] font-black uppercase tracking-[.16em] text-zinc-600">{label}</p><div className={`grid gap-3 ${items.length===1?'grid-cols-1':items.length===2?'grid-cols-2':items.length===3?'grid-cols-3':'grid-cols-4'}`}>{items.map(({product})=><div key={product.id} className="min-w-0 text-xs font-semibold leading-5 text-zinc-200">{render(product)}</div>)}</div></div>)}</div>
      </div>
      <div className="hidden overflow-x-auto rounded-2xl border border-white/[.08] lg:block"><table className="w-full min-w-[760px] border-collapse text-sm"><thead><tr className="bg-white/[.02]"><th className="w-40 p-4 text-left text-xs font-semibold text-autox-gray"></th>{items.map(({product})=><th key={product.id} className="p-4 align-top"><div className="relative rounded-xl border border-white/[.08] bg-[#0b0b0d] p-3"><button onClick={()=>remove(product.id)} aria-label={`Remove ${product.name}`} className="absolute right-2 top-2 flex h-9 w-9 items-center justify-center rounded-full bg-black/60 text-autox-gray hover:text-autox-red"><X size={14}/></button><Link href={`/products/${product.slug}`}>{product.images[0]&&<img src={product.images[0].url} alt={product.images[0].alt} className="mb-3 aspect-square w-full rounded-lg object-cover"/>}<p className="text-left text-sm font-semibold text-white">{product.name}</p><p className="mt-1 text-left text-[10px] text-autox-gray">{product.brand.name}</p></Link><div className="mt-3 flex gap-2"><button disabled={product.stock<=0} onClick={()=>addToCart(product.id)} className="flex h-9 flex-1 items-center justify-center gap-1 rounded-lg bg-autox-red text-[10px] font-black uppercase text-white disabled:opacity-40"><ShoppingCart size={13}/>Cart</button><button onClick={()=>toggleWishlist(product.id)} className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 text-zinc-400"><Heart size={14} className={wishlisted.has(product.id)?'fill-autox-red text-autox-red':''}/></button></div></div></th>)}</tr></thead><tbody><Row label="Price">{items.map(({product})=><td key={product.id} className="p-4"><PriceDisplay price={product.price} previousPrice={product.previousPrice??undefined} size="sm"/></td>)}</Row><Row label="Rating">{items.map(({product})=><td key={product.id} className="p-4"><Rating value={product.rating} reviewCount={product.reviewCount}/></td>)}</Row><Row label="Part Type">{items.map(({product})=><td key={product.id} className="p-4 text-white">{product.partType.replaceAll('_',' ')}</td>)}</Row><Row label="Availability">{items.map(({product})=><td key={product.id} className="p-4 text-white">{product.stock>0?`${product.stock} in stock`:'Out of stock'}</td>)}</Row><Row label="Warranty">{items.map(({product})=><td key={product.id} className="p-4 text-white">{product.warranty}</td>)}</Row>{specs.map(label=><Row key={label} label={label}>{items.map(({product})=><td key={product.id} className="p-4 text-white">{product.specifications.find(s=>s.label===label)?.value||'—'}</td>)}</Row>)}</tbody></table></div>
    </>}
  </section></main>;
}
function Row({label,children}:{label:string;children:React.ReactNode}){return <tr className="border-t border-white/[.07]"><td className="p-4 font-semibold text-autox-gray">{label}</td>{children}</tr>}
