import { Check, ClipboardCheck, Home, Package, PackageCheck, Truck } from "lucide-react";
import { ORDER_STAGES, stageForOrderStatus } from "@/lib/order-status";

type History = { id?: string; status: string; title: string; description: string | null; createdAt: Date | string };
const icons=[ClipboardCheck,PackageCheck,Truck,Package,Home];
function fmt(value:Date|string|undefined){if(!value)return <span className="opacity-50">Pending</span>;const d=new Date(value);return <><span>{d.toLocaleDateString("en-LK",{day:"numeric",month:"short",year:"numeric"})}</span><span>{d.toLocaleTimeString("en-LK",{hour:"2-digit",minute:"2-digit"})}</span></>}
function historyForStage(history:History[],key:string){return history.find(h=>h.status===key || (key==='confirmed'&&(h.status==='paid'||h.status==='processing'||h.status==='confirmed')) || (key==='shipped'&&h.status==='shipped'));}

export function OrderTimeline({status,history,compact=false}:{status:string;history:History[];compact?:boolean}){
 const stage=stageForOrderStatus(status);
 return <div className={compact?"mt-5":"mt-6"}><div className="hidden grid-cols-5 md:grid">{ORDER_STAGES.map((s,i)=>{const active=i<stage;const Icon=icons[i];const h=historyForStage(history,s.key);return <div key={s.key} className="relative flex flex-col items-center text-center">{i<ORDER_STAGES.length-1&&<div className={`absolute left-[calc(50%+20px)] right-[calc(-50%+20px)] top-5 h-px ${i<stage-1?'bg-autox-red':'bg-autox-border'}`}/>}<span className={`relative z-10 flex h-10 w-10 items-center justify-center rounded-full border-2 bg-black ${active?'border-autox-red text-autox-red shadow-[0_0_18px_rgba(237,28,36,.22)]':'border-autox-border text-autox-gray'}`}>{active&&i<stage-1?<Check size={16}/>:<Icon size={16}/>}</span><p className={`mt-2 text-[10px] font-bold uppercase ${active?'text-white':'text-autox-gray'}`}>{s.label}</p><div className="mt-1 flex min-h-8 flex-col text-[9px] leading-4 text-autox-gray">{fmt(h?.createdAt)}</div></div>})}</div>
 <div className="space-y-0 md:hidden">{ORDER_STAGES.map((s,i)=>{const active=i<stage;const Icon=icons[i];const h=historyForStage(history,s.key);return <div key={s.key} className="relative flex gap-3 pb-5 last:pb-0">{i<ORDER_STAGES.length-1&&<div className={`absolute left-[19px] top-10 h-[calc(100%-40px)] w-px ${i<stage-1?'bg-autox-red':'bg-autox-border'}`}/>}<span className={`relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 bg-black ${active?'border-autox-red text-autox-red':'border-autox-border text-autox-gray'}`}><Icon size={16}/></span><div><p className={`text-xs font-bold uppercase ${active?'text-white':'text-autox-gray'}`}>{s.label}</p><div className="mt-1 flex gap-2 text-[10px] text-autox-gray">{fmt(h?.createdAt)}</div></div></div>})}</div></div>;
}

export function TrackingUpdates({history}:{history:History[]}){const sorted=[...history].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());return <div className="mt-4 space-y-0">{sorted.map((h,index)=>{const Icon=h.status==='delivered'?Home:h.status==='out_for_delivery'?Package:h.status==='shipped'?Truck:(h.status==='paid'||h.status==='processing'||h.status==='confirmed')?PackageCheck:ClipboardCheck;return <div key={h.id||`${h.status}-${h.createdAt}`} className="relative flex gap-3 pb-3 last:pb-0">{index<sorted.length-1&&<span className="absolute left-[17px] top-9 h-[calc(100%-36px)] w-px bg-autox-red/50"/>}<span className={`relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border bg-black ${index===0?'border-autox-red text-autox-red':'border-autox-border text-autox-gray'}`}><Icon size={15}/></span><div className="min-w-0 flex-1 rounded-sm border border-autox-border bg-black/25 px-4 py-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-xs font-semibold text-white">{h.title}</p><span className="text-[10px] text-autox-gray">{new Date(h.createdAt).toLocaleString("en-LK",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}</span></div>{h.description&&<p className="mt-1 text-[11px] text-autox-gray">{h.description}</p>}</div></div>})}</div>}
