"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";
import { LayoutDashboard, Package, ShoppingBag, Settings, ArrowLeft, LogOut, Tags, PanelsTopLeft, Boxes, Users, Star, CreditCard, Truck, X, ShieldCheck, ScrollText, MessagesSquare } from "lucide-react";
import { cn } from "@/lib/utils/cn";

type itemLabelKey="Orders"|"Products"|"Reviews"|"Messages"|"Admin Accounts"|"Returns";
type Item={href:string;label:string;icon:React.ElementType};
const groups:{label?:string;items:Item[]}[]=[
  {items:[{href:"/admin",label:"Dashboard",icon:LayoutDashboard}]},
  {label:"Manage",items:[{href:"/admin/orders",label:"Orders",icon:ShoppingBag},{href:"/admin/products",label:"Products",icon:Package},{href:"/admin/catalog",label:"Catalog",icon:Tags},{href:"/admin/inventory",label:"Inventory",icon:Boxes},{href:"/admin/customers",label:"Customers",icon:Users},{href:"/admin/reviews",label:"Reviews",icon:Star},{href:"/admin/messages",label:"Messages",icon:MessagesSquare},{href:"/admin/returns",label:"Returns",icon:ArrowLeft},{href:"/admin/coupons",label:"Coupons",icon:Tags}]},
  {label:"Storefront",items:[{href:"/admin/storefront",label:"Homepage & Footer",icon:PanelsTopLeft}]},
  {label:"Settings",items:[{href:"/admin/settings#payment",label:"Payment Methods",icon:CreditCard},{href:"/admin/settings#shipping",label:"Shipping",icon:Truck},{href:"/admin/settings#store",label:"Store Settings",icon:Settings}]},
];

export function AdminSidebar({mobile=false,onClose,role="admin"}:{mobile?:boolean;onClose?:()=>void;role?:"admin"|"super_admin"}){const pathname=usePathname();const[counts,setCounts]=useState<Record<string,number>>({});useEffect(()=>{fetch("/api/admin/attention-counts",{cache:"no-store"}).then(r=>r.ok?r.json():{}).then(setCounts).catch(()=>{})},[pathname]);const visibleGroups=groups.map(group=>({...group,items:[...group.items]}));if(role==="super_admin")visibleGroups.splice(2,0,{label:"Super Admin",items:[{href:"/admin/admins",label:"Admin Accounts",icon:ShieldCheck},{href:"/admin/security",label:"Security Activity",icon:ScrollText}]});return <aside className={cn("flex h-dvh max-h-dvh w-64 shrink-0 flex-col overflow-hidden border-r border-autox-border bg-[#050505]",mobile&&"w-[280px]")}><div className="flex h-16 items-center border-b border-autox-border px-5"><Link href="/" className="text-xl font-extrabold text-white">AUTO<span className="text-autox-red">X</span></Link><span className="ml-2 rounded border border-autox-border bg-autox-panel3 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-autox-gray">Admin</span>{mobile&&<button onClick={onClose} className="ml-auto text-autox-gray"><X size={18}/></button>}</div><nav className="min-h-0 flex-1 overflow-y-auto overscroll-contain py-4 [scrollbar-color:#3a3a3a_#090909] [scrollbar-width:thin]">{visibleGroups.map((group,g)=><div key={g} className="mb-5">{group.label&&<p className="mb-2 px-5 text-[9px] font-semibold uppercase tracking-[.18em] text-autox-gray/70">{group.label}</p>}{group.items.map(item=>{const base=item.href.split('#')[0];const active=pathname===base||(base!=="/admin"&&pathname.startsWith(base));return <Link onClick={onClose} key={item.href} href={item.href} className={cn("flex h-10 items-center gap-3 border-l-2 px-5 text-sm transition-colors",active?"border-autox-red bg-autox-red/10 text-white":"border-transparent text-autox-gray hover:bg-autox-panel3/50 hover:text-white")}><item.icon size={16} className={active?"text-autox-red":""}/>{item.label}{(()=>{const key:itemLabelKey = item.label as itemLabelKey;const map:Record<itemLabelKey,string>={Orders:"orders",Products:"products",Reviews:"reviews",Messages:"messages","Admin Accounts":"adminAccounts",Returns:"returns"};const n=counts[map[key]]||0;return n>0?<span className="ml-auto min-w-5 rounded-full bg-autox-red px-1.5 text-center text-[9px] font-bold leading-5 text-white">{n>99?"99+":n}</span>:null})()}</Link>})}</div>)}</nav><div className="border-t border-autox-border p-3"><Link href="/" className="flex h-10 items-center gap-3 px-2 text-sm text-autox-gray hover:text-white"><ArrowLeft size={16}/> Back to Store</Link><button onClick={()=>signOut({callbackUrl:'/'})} className="flex h-10 w-full items-center gap-3 px-2 text-sm text-autox-red hover:text-white"><LogOut size={16}/> Sign Out</button></div></aside>}
