"use client";
import { useAppUI } from "@/components/ui/AppUIProvider";
import { useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { AdminImageUpload } from "@/components/admin/AdminImageUpload";
import { uploadAdminImage } from "@/lib/admin/upload-image";
import { HomeCampaignEditor } from "@/components/admin/HomeCampaignEditor";
import { campaignFields, campaignSetting, getHomeCampaign, HomeCampaign } from "@/lib/home-campaigns";

type Slide = { id?: string; eyebrow: string | null; headline: string; headlineAccent: string | null; description: string | null; image: string; mobileImage: string | null; primaryLabel: string; primaryHref: string; secondaryLabel: string | null; secondaryHref: string | null; active: boolean; sortOrder: number };
type Banner = { id?: string; title: string; description: string | null; image: string; ctaLabel: string | null; ctaHref: string | null; active: boolean; sortOrder: number };
const input="w-full rounded-sm border border-autox-border bg-autox-panel3 px-3 py-2 text-sm text-white outline-none focus:border-autox-red";
const label="mb-1 block text-[10px] font-bold uppercase tracking-wide text-autox-gray";
const blankSlide=():Slide=>({ eyebrow:"", headline:"New Hero Slide", headlineAccent:"", description:"", image:"/images/hero/autox-neon-garage-ducati-desktop.webp", mobileImage:"/images/hero/autox-neon-garage-ducati-mobile.webp", primaryLabel:"Shop Parts", primaryHref:"/products", secondaryLabel:"Parts Finder", secondaryHref:"/parts-finder", active:true, sortOrder:0 });
const blankBanner=():Banner=>({ title:"New Promotion", description:"", image:"", ctaLabel:"Shop Now", ctaHref:"/products", active:true, sortOrder:0 });

export function StorefrontManager({ initialSlides, initialBanners, initialSettings, initialBrands, initialCategories }:{ initialSlides:Slide[]; initialBanners:Banner[]; initialSettings:Record<string,string>; initialBrands:{name:string;slug:string;vehicleType:string}[]; initialCategories:{name:string;slug:string}[] }) {
 const{confirm,toast}=useAppUI();
 const [slides,setSlides]=useState(initialSlides); const [banners,setBanners]=useState(initialBanners); const [settings,setSettings]=useState(initialSettings); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [uploadBusy,setUploadBusy]=useState(false);
 const request=async(method:string,body:any)=>{ setBusy(true); setMessage(""); const r=await fetch('/api/admin/storefront',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json().catch(()=>({})); setBusy(false); if(!r.ok){const error=d.error||'Unable to save';setMessage(error);toast(error,'error');return null;} setMessage('Saved successfully.');toast('Storefront changes saved.','success');return d; };
 const reload=async()=>{const r=await fetch('/api/admin/storefront',{cache:'no-store'});if(!r.ok)return;const d=await r.json();setSlides(d.slides??[]);setBanners(d.banners??[]);setSettings(d.settings??{});};
 const upload=async(file:File,done:(url:string)=>void)=>{setUploadBusy(true);setMessage('');try{done(await uploadAdminImage(file));toast('Image uploaded. Save the artwork to keep it.','success')}catch(cause){const error=cause instanceof Error?cause.message:'Image upload failed.';setMessage(error);toast(error,'error')}finally{setUploadBusy(false)}};
 const saveCampaign=async(key:HomeCampaign)=>{const values=getHomeCampaign(key,settings);await request('POST',{type:'settings',data:Object.fromEntries(campaignFields.map(field=>[campaignSetting(key,field),values[field]]))});};
 const saveSlide=async(s:Slide)=>{const d=await request(s.id?'PATCH':'POST',{type:'slide',data:{...s,image:'/images/hero/autox-neon-garage-ducati-desktop.webp',mobileImage:'/images/hero/autox-neon-garage-ducati-mobile.webp'}}); if(d) await reload();};
 const saveBanner=async(b:Banner)=>{const d=await request(b.id?'PATCH':'POST',{type:'banner',data:b}); if(d) await reload();};
 const remove=async(type:'slide'|'banner',id?:string)=>{if(!id)return; const ok=await confirm({title:'Delete storefront item?',description:'This content will be removed from the storefront configuration.',confirmLabel:'Delete',destructive:true});if(!ok)return; const d=await request('DELETE',{type,id}); if(d){await reload();toast('Storefront item deleted.','success');}};
 const artworkField=(title:string,key:string,fallback:string)=> <div key={key}><span className={label}>{title}</span><div className="flex gap-2"><input className={input} value={settings[key]||''} placeholder={fallback||'Image URL'} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))}/><AdminImageUpload compact busy={uploadBusy} title={`Upload ${title}`} onSelect={file=>upload(file,url=>setSettings(s=>({...s,[key]:url})))}/></div></div>;
 const saveArtwork=async(keys:string[])=>{await request('POST',{type:'settings',data:Object.fromEntries(keys.map(k=>[k,settings[k]||'']))});};
 return <div className="space-y-8"><div><h1 className="text-2xl font-extrabold text-white">Storefront</h1><p className="mt-1 text-sm text-autox-gray">Manage homepage hero, promotions, autoplay and footer/social content.</p></div>{message&&<div className="rounded-sm border border-autox-border bg-autox-panel px-4 py-3 text-sm text-autox-gray">{message}</div>}
 <section className="rounded-md border border-autox-border bg-autox-panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-white">Hero Slider Settings</h2><p className="text-xs text-autox-gray">Multiple active slides automatically become the homepage slider.</p></div><button disabled={busy} onClick={()=>request('POST',{type:'settings',data:settings})} className="flex items-center gap-2 rounded-sm bg-autox-red px-4 py-2 text-xs font-bold text-white"><Save size={14}/> Save Settings</button></div><div className="grid gap-4 md:grid-cols-3"><label><span className={label}>Autoplay</span><select className={input} value={settings.hero_autoplay||'true'} onChange={e=>setSettings(s=>({...s,hero_autoplay:e.target.value}))}><option value="true">On</option><option value="false">Off</option></select></label><label><span className={label}>Slide interval (ms)</span><input type="number" min="2000" step="500" className={input} value={settings.hero_interval||'5000'} onChange={e=>setSettings(s=>({...s,hero_interval:e.target.value}))}/></label><label><span className={label}>Pause on hover</span><select className={input} value={settings.hero_pause_hover||'true'} onChange={e=>setSettings(s=>({...s,hero_pause_hover:e.target.value}))}><option value="true">On</option><option value="false">Off</option></select></label></div></section>
 <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold text-white">Hero Slides</h2><button onClick={()=>setSlides(x=>[...x,blankSlide()])} className="flex items-center gap-2 text-xs font-bold text-autox-red"><Plus size={14}/> Add Slide</button></div>{slides.map((s,i)=><div key={s.id||`new-${i}`} className="rounded-md border border-autox-border bg-autox-panel p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label><span className={label}>Headline</span><input className={input} value={s.headline} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,headline:e.target.value}:v))}/></label><label><span className={label}>Accent text</span><input className={input} value={s.headlineAccent||''} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,headlineAccent:e.target.value}:v))}/></label><label className="lg:col-span-2"><span className={label}>Description</span><input className={input} value={s.description||''} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,description:e.target.value}:v))}/></label><p className="md:col-span-2 lg:col-span-4 rounded-md border border-autox-red/20 bg-autox-red/[.045] px-3 py-2 text-xs text-autox-gray">The neon garage and motorcycle stay fixed on desktop and mobile. These slides change only the headline, description, and buttons.</p><label><span className={label}>Primary label</span><input className={input} value={s.primaryLabel} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,primaryLabel:e.target.value}:v))}/></label><label><span className={label}>Primary URL</span><input className={input} value={s.primaryHref} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,primaryHref:e.target.value}:v))}/></label><label><span className={label}>Order</span><input type="number" className={input} value={s.sortOrder} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,sortOrder:Number(e.target.value)}:v))}/></label><label><span className={label}>Active</span><select className={input} value={String(s.active)} onChange={e=>setSlides(x=>x.map((v,j)=>j===i?{...v,active:e.target.value==='true'}:v))}><option value="true">Yes</option><option value="false">No</option></select></label></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>remove('slide',s.id)} disabled={!s.id} className="rounded-sm border border-autox-border px-3 py-2 text-xs text-autox-gray disabled:opacity-30"><Trash2 size={14}/></button><button disabled={busy} onClick={()=>saveSlide(s)} className="rounded-sm bg-autox-red px-4 py-2 text-xs font-bold text-white">Save Slide</button></div></div>)}</section>
 <HomeCampaignEditor settings={settings} change={(key,value)=>setSettings(current=>({...current,[key]:value}))} save={saveCampaign} upload={(key,file)=>upload(file,url=>setSettings(current=>({...current,[campaignSetting(key,'image')]:url})))} busy={busy} uploadBusy={uploadBusy}/>
 <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold text-white">Additional Promo Banners</h2><button onClick={()=>setBanners(x=>[...x,blankBanner()])} className="flex items-center gap-2 text-xs font-bold text-autox-red"><Plus size={14}/> Add Banner</button></div>{banners.map((b,i)=><div key={b.id||`b-${i}`} className="rounded-md border border-autox-border bg-autox-panel p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label><span className={label}>Title</span><input className={input} value={b.title} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,title:e.target.value}:v))}/></label><label><span className={label}>CTA label</span><input className={input} value={b.ctaLabel||''} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,ctaLabel:e.target.value}:v))}/></label><label className="lg:col-span-2"><span className={label}>Description</span><input className={input} value={b.description||''} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,description:e.target.value}:v))}/></label><div className="md:col-span-2"><span className={label}>Background image</span><div className="flex gap-2"><input className={input} value={b.image} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,image:e.target.value}:v))}/><AdminImageUpload compact busy={uploadBusy} title="Upload banner image" onSelect={file=>upload(file,url=>setBanners(x=>x.map((v,j)=>j===i?{...v,image:url}:v)))}/></div></div><label><span className={label}>CTA URL</span><input className={input} value={b.ctaHref||''} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,ctaHref:e.target.value}:v))}/></label><label><span className={label}>Order</span><input type="number" className={input} value={b.sortOrder} onChange={e=>setBanners(x=>x.map((v,j)=>j===i?{...v,sortOrder:Number(e.target.value)}:v))}/></label></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>remove('banner',b.id)} disabled={!b.id} className="rounded-sm border border-autox-border px-3 py-2 text-xs text-autox-gray disabled:opacity-30"><Trash2 size={14}/></button><button onClick={()=>saveBanner(b)} disabled={busy||uploadBusy||!b.image.trim()} className="rounded-sm bg-autox-red px-4 py-2 text-xs font-bold text-white">Save Banner</button></div></div>)}</section>
 <section className="space-y-4"><div><h2 className="text-lg font-bold text-white">Brand Card & Page Artwork</h2><p className="text-xs text-autox-gray">Upload a separate vehicle scene, transparent logo and brand-page hero for each brand. Blank fields use the default artwork or catalog image.</p></div>{initialBrands.map(b=>{const fields=[{title:'Card vehicle / background',key:`brand_card_image_${b.slug}`,fallback:`/images/brand-cards/${b.slug}.webp`},{title:'Transparent logo',key:`brand_card_logo_${b.slug}`,fallback:`/images/brand-cards/${b.slug}-logo.webp`},{title:'Brand page hero',key:`brand_hero_image_${b.slug}`,fallback:`/images/brand-heroes/${b.slug}.webp`}];return <div key={b.slug} className="rounded-md border border-autox-border bg-autox-panel p-4"><div className="mb-3 flex items-center justify-between gap-2"><h3 className="text-sm font-bold text-white">{b.name} <span className="font-normal text-autox-gray">({b.vehicleType})</span></h3><button disabled={busy||uploadBusy} onClick={()=>saveArtwork(fields.map(f=>f.key))} className="flex items-center gap-1 rounded-sm bg-autox-red px-3 py-2 text-xs font-bold text-white"><Save size={14}/> Save Artwork</button></div><div className="grid gap-3 md:grid-cols-3">{fields.map(f=>artworkField(f.title,f.key,f.fallback))}</div></div>})}</section>
 <section className="space-y-4"><div><h2 className="text-lg font-bold text-white">Shop By Category Artwork</h2><p className="text-xs text-autox-gray">Upload a category garage scene and an optional transparent icon. The product count still comes from the catalog.</p></div>{initialCategories.map(c=>{const keys=[`category_card_image_${c.slug}`,`category_icon_image_${c.slug}`];return <div key={c.slug} className="rounded-md border border-autox-border bg-autox-panel p-4"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-bold text-white">{c.name}</h3><button disabled={busy||uploadBusy} onClick={()=>saveArtwork(keys)} className="flex items-center gap-1 rounded-sm bg-autox-red px-3 py-2 text-xs font-bold text-white"><Save size={14}/> Save Artwork</button></div><div className="grid gap-3 md:grid-cols-2">{artworkField('Card background',keys[0],`/images/category-cards/${c.slug}.webp`)}{artworkField('Transparent category icon',keys[1],'Uses existing category icon')}</div></div>})}</section>
 <section className="rounded-md border border-autox-border bg-autox-panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-white">Footer & Social Media</h2><p className="text-xs text-autox-gray">Blank social URLs stay hidden on the storefront.</p></div><button disabled={busy} onClick={()=>request('POST',{type:'settings',data:settings})} className="flex items-center gap-2 rounded-sm bg-autox-red px-4 py-2 text-xs font-bold text-white"><Save size={14}/> Save Footer</button></div><div className="grid gap-4 md:grid-cols-2"><label><span className={label}>Copyright text (year is automatic)</span><input className={input} value={settings.footer_copyright||''} onChange={e=>setSettings(s=>({...s,footer_copyright:e.target.value}))}/></label><label><span className={label}>Bottom text</span><input className={input} value={settings.footer_bottom_text||''} onChange={e=>setSettings(s=>({...s,footer_bottom_text:e.target.value}))}/></label>{['facebook','instagram','youtube','tiktok','whatsapp','x'].map(k=><label key={k}><span className={label}>{k} URL</span><input className={input} value={settings[`social_${k}`]||''} onChange={e=>setSettings(s=>({...s,[`social_${k}`]:e.target.value}))}/></label>)}</div></section>
 </div>;
}
