import { db } from "@/db";
import { users, orders } from "@/db/schema";
import { and, desc, eq, ilike, or, sql } from "drizzle-orm";
import { formatPrice } from "@/lib/utils/format";
import { Search } from "lucide-react";
import { Pagination } from "@/components/ui/Pagination";
import { parsePagination } from "@/lib/pagination";
export const dynamic="force-dynamic";
export default async function CustomersPage({searchParams}:{searchParams:Promise<{q?:string;page?:string;limit?:string}>}){const params=await searchParams;const q=params.q?.trim()||"";const {page,limit,offset}=parsePagination(params);const term=`%${q}%`;const where=q?and(eq(users.role,'customer'),or(ilike(users.name,term),ilike(users.email,term),ilike(users.phone,term))):eq(users.role,'customer');const [rows,countRows]=await Promise.all([db.select({id:users.id,name:users.name,email:users.email,phone:users.phone,createdAt:users.createdAt,orders:sql<number>`count(${orders.id})::int`,spent:sql<number>`coalesce(sum(case when ${orders.status} != 'cancelled' then ${orders.total} else 0 end),0)::float`}).from(users).leftJoin(orders,eq(orders.userId,users.id)).where(where).groupBy(users.id).orderBy(desc(users.createdAt)).limit(limit).offset(offset),db.select({count:sql<number>`count(*)::int`}).from(users).where(where)]);const total=countRows[0]?.count??0;return <div><div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-extrabold text-white">Customers</h1><p className="mt-1 text-sm text-autox-gray">{total} customer account{total===1?'':'s'}.</p></div><form className="flex h-10 w-full max-w-md overflow-hidden rounded-sm border border-autox-border bg-autox-panel focus-within:border-autox-red"><input name="q" defaultValue={q} placeholder="Search customer name, email or phone..." className="min-w-0 flex-1 appearance-none bg-transparent px-3 text-sm text-white outline-none ring-0 focus:outline-none focus:ring-0 focus-visible:outline-none"/><button className="grid w-11 place-items-center bg-autox-red text-white focus:outline-none focus-visible:outline-none" aria-label="Search customers"><Search size={15}/></button></form></div><div className="overflow-hidden rounded-md border border-autox-border bg-autox-panel"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs"><thead className="bg-black/30 text-left uppercase text-autox-gray"><tr><th className="px-5 py-3">Customer</th><th>Phone</th><th>Orders</th><th>Total Spent</th><th>Member Since</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t border-autox-border/70"><td className="px-5 py-3"><p className="font-semibold text-white">{c.name||'Customer'}</p><p className="mt-1 text-[10px] text-autox-gray">{c.email}</p></td><td className="text-autox-gray">{c.phone||'—'}</td><td className="text-white">{c.orders}</td><td className="font-semibold text-white">{formatPrice(c.spent)}</td><td className="text-autox-gray">{new Date(c.createdAt).toLocaleDateString('en-LK',{day:'numeric',month:'short',year:'numeric'})}</td></tr>)}</tbody></table></div>{rows.length===0&&<p className="p-5 text-sm text-autox-gray">No customers match this search.</p>}</div><Pagination page={page} pageSize={limit} total={total} pathname="/admin/customers" params={{q}}/></div>}
